# https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
# https://github.com/<your_enterprise/org/repo>
githubConfigUrl: "https://github.com/konvenit"
githubConfigSecret: github-pat
minRunners: 2
# maxRunners: 10
template:
  spec:
    initContainers:
    - name: init-dind-externals
      image: ghcr.io/actions/actions-runner:latest
      command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
      volumeMounts:
        - name: dind-externals
          mountPath: /home/runner/tmpDir
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      env:
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-sock
          mountPath: /var/run
        - name: toolcache
          mountPath: /opt/hostedtoolcache
    - name: dind
      image: docker:dind
      args:
        - dockerd
        - --host=unix:///var/run/docker.sock
        - --group=$(DOCKER_GROUP_GID)
        - --max-concurrent-downloads=5
        - --http-proxy=http://proxy20.boreus.de:3128/
        - --https-proxy=http://proxy20.boreus.de:3128/
        - --no-proxy=127.0.0.1,localhost,localhost.localdomain,cluster.local,10.43.0.1,miceportal-alpha.de,miceportal-alpha.com,miceportal.de,miceportal.com,svc.boreus.de,mice.boreus.de,registry.boreus.de,gitlab.boreus.de,*.nexus-registry-mice.boreus.de
      env:
        - name: DOCKER_GROUP_GID
          value: "123"
      securityContext:
        privileged: true
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
        - name: dind-sock
          mountPath: /var/run
        - name: dind-externals
          mountPath: /home/runner/externals
    volumes:
    - name: work
      emptyDir: {}
    - name: dind-sock
      emptyDir: {}
    - name: dind-externals
      emptyDir: {}
    - name: toolcache
      emptyDir: {}
    nodeSelector: {
      "ci": "true"
    }
    tolerations: [
      {
        "key": "ci",
        "operator": "Equal",
        "value": "true",
        "effect": "NoSchedule"
      }
    ]
listenerTemplate:
  spec:
    containers:
      - name: listener
        securityContext:
          runAsUser: 1000
    nodeSelector: {
      "ci": "true"
    }
    tolerations: [
      {
        "key": "ci",
        "operator": "Equal",
        "value": "true",
        "effect": "NoSchedule"
      }
    ]
