name: compose build and up
description: Runs docker-compose up and waits for stuff to start properly

inputs:
  application-name:
    required: true
    type: string

runs:
  using: composite
  steps:
  - shell: bash
    run: |
      echo "::group::>>> Pull dependencies"
      docker-compose -f docker-compose.test.yml pull 2>&1 | grep -v -E '^Pulling .*\.\. (extracting |downloading |waiting|pulling fs |verifying checksum|download complete)'
      echo "::endgroup::"

  - shell: bash
    run: |
      echo "::group::>>> docker-compose up"
      docker-compose -f docker-compose.test.yml up -d
      echo "::endgroup::"

  - shell: bash
    run: |
      echo "::group::>>> prepare database"
      docker-compose -f docker-compose.test.yml exec -T ${{ inputs.application-name }} bin/rails db:drop db:create db:test:prepare
      echo "::endgroup::"

  - shell: bash
    run: |
      echo "::group::>>> Wait while starting"
      sleep 5
      tries=20
      while :; do
        tries=$(( tries - 1 ))
        SERVICES=$(docker-compose -f docker-compose.test.yml ps)
        if echo $SERVICES | grep -q '(health: starting)'
        then
          echo " -- Still waiting ($tries more) ..."
          echo
          echo "$SERVICES" | grep '(health: starting)'
          if [[ $tries -lt 0 ]]; then
            echo "Too many retries. Giving up."
            echo "::error title=Starting timed out::Some services are still starting. Too many retries."
            exit 1
          fi
          sleep 2
        else
          echo " -- No more starting services..."
          echo "$SERVICES"
          break
        fi
      done
      echo "::endgroup::"

  - shell: bash
    run: |
      echo "::group::>>> Count started services"
      n=$(ruby -e "require 'yaml'; print YAML.safe_load('docker-compose.test.yml')['services'].count")
      echo " --- Checking if all ${n} services are running..."
      RUNNING=$(docker-compose -f docker-compose.test.yml ps --services --filter "status=running" | wc -l)
      if [ "$RUNNING" != "$n" ]; then
        echo "  -- not all services are running"
        echo "::error title=Starting failed::Not all expected services are running"
        docker-compose -f docker-compose.test.yml logs
        exit 1
      fi
      echo "::endgroup::"

  - shell: bash
    run: |
      echo "::group::>>> Check if app is healthy"
      STATUS=$(docker inspect --format "{{.State.Health.Status}}" $(docker-compose -f docker-compose.test.yml ps -q ${{ inputs.application-name}}))
      if [ "$STATUS" != "healthy" ]
      then
        echo "${{ inputs.application-name }} is not healthy:"
        echo "::error title=Not healthy::The app is not in healthy status: ${STATUS}"
        docker-compose -f docker-compose.test.yml ps
        exit 1
      fi
      echo "::endgroup::"
