name: docker compose build and push to docker hub

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: ${{ github.event.pull_request.head.sha || github.sha }}
      push_to_docker_hub:
        required: false
        default: true
        type: boolean
    secrets:
      nexus_user:
        required: true
      nexus_pass:
        required: true

env:
  TAG: ${{ inputs.tag }}

jobs:
  compose_push:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Setup Nexus Access
      run: |
        echo "$(dig +short mice-prod-web01.dns.boreus.de) miceportal.nexus-registry-mice.boreus.de" | sudo tee -a /etc/hosts
        docker login miceportal.nexus-registry-mice.boreus.de -u ${{ secrets.nexus_user }} -p ${{ secrets.nexus_pass }}

    - name: Compose up
      uses: konvenit/workflowator/.github/actions/compose@v12
      with:
        application-name: ${{ inputs.application-name }}

    - name: Push Docker image to Nexus
      if: ${{ inputs.push_to_docker_hub }}
      run: docker compose -f docker-compose.test.yml push ${{ inputs.application-name}}

    - name: Stop containers
      if: always()
      run: docker compose -f docker-compose.test.yml down
