name: Sample github action

on:
  workflow_call:
    inputs:
      enable-code-scans:
        required: false
        type: boolean
    secrets:
      ghcr-token:
        required: true
        description: Github token allowing access to the libraries and ghcr.

jobs:
  sample-action:
    name: Sample action
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run sample action
        run: |
          echo "Running sample action"
          echo "ghcr-token: ${{ secrets.ghcr-token }}"
          echo "enable-code-scans: ${{ inputs.enable-code-scans }}"
